services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: # this done in dockerfile already bundle exec rails server -b 0.0.0.0 -p 3000
    depends_on:
      db: 
        condition: service_healthy
      stripe-cli:
        condition: service_started
    env_file: .env_dev  # Use environment file
    environment:
      WEBHOOK_URL: http://app:3000/stripe/webhook
      DB_HOST: db
    networks:
      - project_network
    ports:
      - "3000:3000"  # Simplified port mapping
    volumes:
      - .:/app
      - bundle:/usr/local/bundle

  db:
    image: postgres:16
    env_file: .env_dev  # Add this line
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - project_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  stripe-cli:
    image: stripe/stripe-cli:latest
    env_file: .env
    command: listen --api-key ${STRIPE_SECRET_KEY} --forward-to http://app:3000/stripe/webhook
    networks:
      - project_network
    volumes:  
      - ./stripe-cli-output:/output
networks:
  project_network:
    name: project_default

volumes:
  bundle:
    name: project_bundle
  postgres_data:
    name: project_postgres_data
    #- bash
    #- -c
    #- bundle install && rm -f tmp/pids/server.pid && rails server -b 0.0.0.0
