services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: 
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file: .env_dev  # Use environment file
    environment:
      DB_HOST: db
      REDIS_URL: redis://redis:6379/1
    networks:
      - project_network
    ports:
      - "3000:3000"  # Simplified port mapping
    volumes:
      - .:/app
      - bundle:/usr/local/bundle

  db:
    image: postgres:16
    env_file: .env_dev  # Add this line
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - project_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-dev
    ports:
      - "6379:6379"
    networks:
      - project_network

networks:
  project_network:
    name: project_default

volumes:
  bundle:
    name: project_bundle
  postgres_data:
    name: project_postgres_data
    #- bash
    #- -c
    #- bundle install && rm -f tmp/pids/server.pid && rails server -b 0.0.0.0
